// This file is generated by generate-std.joke script. Do not edit manually!

package pop3

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of pop3.InternsOrThunks().")
	}
	pop3Namespace.ResetMeta(MakeMeta(nil, `Retrieves raw email messages from POP3 mailboxes using explicit client sessions.`, "1.0"))

	pop3Namespace.InternVar("capabilities", capabilities_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol))),
			`Returns the server CAPA response as a map of capability strings to vectors
  of argument strings.

  For example, a response containing UIDL and SASL PLAIN becomes
  {"UIDL" [] "SASL" ["PLAIN"]}. Throws Error when CAPA is unsupported or
  the session cannot complete the operation.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Map"}))

	pop3Namespace.InternVar("close", close_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol))),
			`Closes client without sending QUIT and returns nil.

  Use close to abandon a session without committing deletion marks. close is
  idempotent; the POP3Client is unusable afterward.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	pop3Namespace.InternVar("connect", connect_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("opts").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol))),
			`Connects to a POP3 server, authenticates, and returns a POP3Client session.

  opts is a map with the following keys:
  - addr (string, required): server address, such as "pop.example.com:995".
  - username (string, required): USER authentication value.
  - password (string, required): PASS authentication value.
  - tls (keyword, string, or symbol, optional): :implicit (default),
    :starttls, or :none.
  - server-name (string, optional): TLS certificate hostname override. By
    default the host portion of :addr is used.
  - timeout-ms (int, optional): positive timeout applied separately to
    connecting, TLS negotiation, authentication, and each later operation.
    If omitted, operations have no configured timeout.

  :implicit establishes TLS before reading the POP3 greeting. :starttls reads
  the greeting, issues STLS, and then establishes TLS before authentication.
  :none sends credentials on an unencrypted connection and must be selected
  explicitly.

  Authentication uses USER and PASS. connect throws Error on configuration,
  network, TLS, protocol, or authentication failure.

  Example:
    (def client
      (joker.pop3/connect {:addr "pop.example.com:995"
                           :tls :implicit
                           :username "user@example.com"
                           :password "secret"
                           :timeout-ms 30000}))`, "1.8").Plus(MakeKeyword("tag"), String{S: "POP3Client"}))

	pop3Namespace.InternVar("delete", delete_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol), MakeSymbol("number").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Int"}).(Map)).(Symbol))),
			`Marks message number for deletion and returns nil.

  POP3 applies marked deletions only after a successful quit. Use reset to
  clear deletion marks or close to abort a session without issuing QUIT.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	pop3Namespace.InternVar("list", list_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol)), NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol), MakeSymbol("number").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Int"}).(Map)).(Symbol))),
			`Returns POP3 message size information.

  With one argument, returns a vector of {:number n :octets size} maps for all
  available messages. With number, returns the size map for that message.
  Throws Error when the server rejects the request or responds incorrectly.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Seqable"}))

	pop3Namespace.InternVar("noop", noop_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol))),
			`Sends POP3 NOOP to keep a session active or check connectivity and returns
  nil.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	pop3Namespace.InternVar("quit", quit_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol))),
			`Sends QUIT, commits server-side deletions marked in this session, closes the
  connection, and returns nil.

  The POP3Client is unusable after quit, including when QUIT fails.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	pop3Namespace.InternVar("reset", reset_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol))),
			`Clears any deletion marks in the current session and returns nil.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	pop3Namespace.InternVar("retrieve", retrieve_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol), MakeSymbol("number").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Int"}).(Map)).(Symbol))),
			`Retrieves the complete raw RFC 5322 message for message number.

  Returns the message as a string with POP3 dot-stuffing removed and CRLF line
  endings preserved. The complete message is buffered in memory. This function
  does not parse MIME content or headers.`, "1.8").Plus(MakeKeyword("tag"), String{S: "String"}))

	pop3Namespace.InternVar("stat", stat_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol))),
			`Returns mailbox statistics as {:count n :octets size}.

  :count is the number of messages in the mailbox and :octets is their
  combined reported size.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Map"}))

	pop3Namespace.InternVar("top", top_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol), MakeSymbol("number").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Int"}).(Map)).(Symbol), MakeSymbol("lines").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Int"}).(Map)).(Symbol))),
			`Retrieves message headers and up to lines body lines for message number.

  TOP is an optional POP3 command; unsupported servers cause Error. The
  returned raw message fragment has POP3 dot-stuffing removed and CRLF line
  endings preserved. lines must be non-negative.`, "1.8").Plus(MakeKeyword("tag"), String{S: "String"}))

	pop3Namespace.InternVar("uidl", uidl_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol)), NewVectorFrom(MakeSymbol("client").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "POP3Client"}).(Map)).(Symbol), MakeSymbol("number").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Int"}).(Map)).(Symbol))),
			`Returns POP3 unique identifiers.

  With one argument, returns a vector of {:number n :uid id} maps for all
  available messages. With number, returns the identifier map for that
  message. UIDL is an optional POP3 command; unsupported servers cause Error.`, "1.8").Plus(MakeKeyword("tag"), String{S: "Seqable"}))

}
