// This file is generated by generate-std.joke script. Do not edit manually!

package pop3

import (
	. "github.com/candid82/joker/core"
)

var __capabilities__P ProcFn = __capabilities_
var capabilities_ Proc = Proc{Fn: __capabilities__P, Name: "capabilities_", Package: "std/pop3"}

func __capabilities_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := capabilities(client)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __close__P ProcFn = __close_
var close_ Proc = Proc{Fn: __close__P, Name: "close_", Package: "std/pop3"}

func __close_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := close(client)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __connect__P ProcFn = __connect_
var connect_ Proc = Proc{Fn: __connect__P, Name: "connect_", Package: "std/pop3"}

func __connect_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		opts := ExtractMap(_args, 0)
		_res := connect(opts)
		return MakePOP3Client(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

var __delete__P ProcFn = __delete_
var delete_ Proc = Proc{Fn: __delete__P, Name: "delete_", Package: "std/pop3"}

func __delete_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 2:
		client := ExtractPOP3Client(_args, 0)
		number := ExtractInt(_args, 1)
		_res := deleteMessage(client, number)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __list__P ProcFn = __list_
var list_ Proc = Proc{Fn: __list__P, Name: "list_", Package: "std/pop3"}

func __list_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := listAll(client)
		return _res

	case _c == 2:
		client := ExtractPOP3Client(_args, 0)
		number := ExtractInt(_args, 1)
		_res := listOne(client, number)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __noop__P ProcFn = __noop_
var noop_ Proc = Proc{Fn: __noop__P, Name: "noop_", Package: "std/pop3"}

func __noop_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := noop(client)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __quit__P ProcFn = __quit_
var quit_ Proc = Proc{Fn: __quit__P, Name: "quit_", Package: "std/pop3"}

func __quit_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := quit(client)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __reset__P ProcFn = __reset_
var reset_ Proc = Proc{Fn: __reset__P, Name: "reset_", Package: "std/pop3"}

func __reset_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := reset(client)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __retrieve__P ProcFn = __retrieve_
var retrieve_ Proc = Proc{Fn: __retrieve__P, Name: "retrieve_", Package: "std/pop3"}

func __retrieve_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 2:
		client := ExtractPOP3Client(_args, 0)
		number := ExtractInt(_args, 1)
		_res := retrieve(client, number)
		return MakeString(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

var __stat__P ProcFn = __stat_
var stat_ Proc = Proc{Fn: __stat__P, Name: "stat_", Package: "std/pop3"}

func __stat_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := stat(client)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __top__P ProcFn = __top_
var top_ Proc = Proc{Fn: __top__P, Name: "top_", Package: "std/pop3"}

func __top_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 3:
		client := ExtractPOP3Client(_args, 0)
		number := ExtractInt(_args, 1)
		lines := ExtractInt(_args, 2)
		_res := top(client, number, lines)
		return MakeString(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

var __uidl__P ProcFn = __uidl_
var uidl_ Proc = Proc{Fn: __uidl__P, Name: "uidl_", Package: "std/pop3"}

func __uidl_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		client := ExtractPOP3Client(_args, 0)
		_res := uidlAll(client)
		return _res

	case _c == 2:
		client := ExtractPOP3Client(_args, 0)
		number := ExtractInt(_args, 1)
		_res := uidlOne(client, number)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var pop3Namespace = GLOBAL_ENV.EnsureSymbolIsLib(MakeSymbol("joker.pop3"))

func init() {
	pop3Namespace.Lazy = Init
}
