// This file is generated by generate-std.joke script. Do not edit manually!

package git

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of git.InternsOrThunks().")
	}
	gitNamespace.ResetMeta(MakeMeta(nil, `Reads and mutates local Git repositories through go-git-backed map-oriented wrappers.`, "1.0"))

	gitNamespace.InternVar("add-commit", add_commit_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol), MakeSymbol("msg").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("opts").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol))),
			`Creates a commit from the current index and returns its hash string.

  msg is the commit message. opts may contain:
  - all - truthy to stage modified and deleted tracked files before committing
  - allow-empty-commits - truthy to permit a commit with no tree changes
  Throws Error when the worktree cannot commit.`, "1.4").Plus(MakeKeyword("tag"), String{S: "String"}))

	gitNamespace.InternVar("add-path", add_path_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol), MakeSymbol("path").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Stages path from the worktree into the index and returns a hash string.

  Existing staged files may be staged again. Deleted files are removed from the
  index. Directory paths are added recursively. Throws Error when the worktree
  cannot be accessed or the path cannot be staged.`, "1.4").Plus(MakeKeyword("tag"), String{S: "String"}))

	gitNamespace.InternVar("commit", commit_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol), MakeSymbol("hash").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Returns the commit map for hash.

  The result has the same shape as entries returned by joker.git/log. Throws
  Error when hash does not name a commit.`, "1.3").Plus(MakeKeyword("tag"), String{S: "Map"}))

	gitNamespace.InternVar("config", config_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol))),
			`Returns repo configuration as a map.

  The map includes core properties such as :bare?, :worktree, :default-branch,
  :user, :author, :committer, :remotes, :submodules, :branches, and :urls.
  Throws Error when the configuration cannot be read.`, "1.3").Plus(MakeKeyword("tag"), String{S: "Map"}))

	gitNamespace.InternVar("head", head_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol))),
			`Returns the repository HEAD reference map.

  The returned map has the same shape as joker.git/ref. Throws Error when HEAD
  cannot be resolved.`, "1.3").Plus(MakeKeyword("tag"), String{S: "Map"}))

	gitNamespace.InternVar("log", log_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol), MakeSymbol("opts").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol))),
			`Returns commit history as a vector of commit maps.

  Each commit map contains :hash, :author, :committer, :message, :tree-hash,
  :parent-hashes, and :pgp-signature. Signature maps contain :name, :email, and
  :when.

  opts may have the following keys:

  :from - commit hash string from which traversal starts. When set, the log
  only contains commits
  reachable from it. If this option is not set, HEAD will be used as
  the default from.

  :order - one of :default, :dfs, :dfs-post, :bsf, or :committer-time. The
  default traversal is depth-first search. :committer-time is closer to
  ordinary `+"`"+`git log`+"`"+` ordering.

  :path-filter - filter commits based on the path of files that are updated.
  The fn receives each path string and should return truthy for desired paths.
  It can be used to implement `+"`"+`git log -- <path>`+"`"+`.

  :all - pretend as if all the refs in refs/, along with HEAD, are listed on the command line as <commit>.
  It is equivalent to running `+"`"+`git log --all`+"`"+`.
  If set to true, the :from option will be ignored.

  :since - show commits more recent than a specific date.
  It is equivalent to running `+"`"+`git log --since <date>`+"`"+` or `+"`"+`git log --after <date>`+"`"+`.

  :until - show commits older than a specific date.
  It is equivalent to running `+"`"+`git log --until <date>`+"`"+` or `+"`"+`git log --before <date>`+"`"+`.

  Throws Error when traversal cannot be started or completed, or when :order
  has an unsupported value.`, "1.3").Plus(MakeKeyword("tag"), String{S: "Vec"}))

	gitNamespace.InternVar("object", object_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol), MakeSymbol("hash").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Returns a summary map for the Git object with hash.

  The map contains :id and :type, where :type is one of :commit, :tree, :blob,
  :tag, :ofs-delta, :ref-delta, :any, or :invalid. Throws Error when no object
  can be found.`, "1.3").Plus(MakeKeyword("tag"), String{S: "Map"}))

	gitNamespace.InternVar("open", open_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("path").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Opens the Git repository at path and returns a GitRepo handle.

  Detects both bare and worktree repositories. Throws Error when path does not
  contain a valid repository or the repository cannot be opened.`, "1.3").Plus(MakeKeyword("tag"), String{S: "GitRepo"}))

	gitNamespace.InternVar("ref", ref_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol), MakeSymbol("name").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("resolved").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Boolean"}).(Map)).(Symbol))),
			`Returns reference name as a map.

  If resolved is true, symbolic references are resolved before being returned.
  The result contains :type (:hash, :symbolic, or :invalid), :name, :target,
  and :hash. Throws Error when the reference cannot be found.`, "1.3").Plus(MakeKeyword("tag"), String{S: "Map"}))

	gitNamespace.InternVar("resolve-revision", resolve_revision_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("repo").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "GitRepo"}).(Map)).(Symbol), MakeSymbol("revision").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Resolves revision to a commit hash string.

  The result is always the commit hash, not a tree hash or annotated-tag hash.
  Throws Error when revision cannot be resolved.`, "1.3").Plus(MakeKeyword("tag"), String{S: "String"}))

}
