// This file is generated by generate-std.joke script. Do not edit manually!

package url

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of url.InternsOrThunks().")
	}
	urlNamespace.ResetMeta(MakeMeta(nil, `Escapes URL path/query components and parses URL-encoded query strings.`, "1.0"))

	urlNamespace.InternVar("parse-query", parse_query_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Parses URL-encoded query string s into a map of string keys to value vectors.

  Always returns a map containing the valid query parameters found.
  Query is expected to be a list of key=value settings separated by ampersands. A setting without
  an equals sign is interpreted as a key set to an empty value. Settings containing a non-URL-encoded
  semicolon or malformed escapes are considered invalid and are omitted rather
  than thrown.`, "1.3.6"))

	urlNamespace.InternVar("path-escape", path_escape_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Escapes the string so it can be safely placed inside a URL path segment.`, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

	urlNamespace.InternVar("path-unescape", path_unescape_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Reverses path-escape for one URL path segment.

  Converts percent-encoded substrings such as "%2F" to their bytes. Unlike
  query-unescape, it leaves '+' unchanged. Throws Error when a percent escape is
  malformed.`, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

	urlNamespace.InternVar("query-escape", query_escape_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Escapes the string so it can be safely placed inside a URL query.`, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

	urlNamespace.InternVar("query-unescape", query_unescape_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Reverses query-escape for query text.

  Converts percent-encoded substrings such as "%2F" to their bytes and '+'
  into space. Throws Error when a percent escape is malformed.`, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

}
