// This file is generated by generate-std.joke script. Do not edit manually!

package mail

import (
	. "github.com/candid82/joker/core"
)

var __parse_address__P ProcFn = __parse_address_
var parse_address_ Proc = Proc{Fn: __parse_address__P, Name: "parse_address_", Package: "std/mail"}

func __parse_address_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		s := ExtractString(_args, 0)
		_res := parseAddress(s)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __parse_address_list__P ProcFn = __parse_address_list_
var parse_address_list_ Proc = Proc{Fn: __parse_address_list__P, Name: "parse_address_list_", Package: "std/mail"}

func __parse_address_list_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		s := ExtractString(_args, 0)
		_res := parseAddressList(s)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __parse_date__P ProcFn = __parse_date_
var parse_date_ Proc = Proc{Fn: __parse_date__P, Name: "parse_date_", Package: "std/mail"}

func __parse_date_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		s := ExtractString(_args, 0)
		_res := parseDate(s)
		return MakeTime(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

var __read_message__P ProcFn = __read_message_
var read_message_ Proc = Proc{Fn: __read_message__P, Name: "read_message_", Package: "std/mail"}

func __read_message_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		source := ExtractObject(_args, 0)
		_res := readMessage(source)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var mailNamespace = GLOBAL_ENV.EnsureSymbolIsLib(MakeSymbol("joker.mail"))

func init() {
	mailNamespace.Lazy = Init
}
