// This file is generated by generate-std.joke script. Do not edit manually!

package mail

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of mail.InternsOrThunks().")
	}
	mailNamespace.ResetMeta(MakeMeta(nil, `Parses raw RFC 5322 email messages, address fields, and mail dates.`, "1.0"))

	mailNamespace.InternVar("parse-address", parse_address_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Parses one RFC 5322 email address and returns
  {:name display-name :address mailbox}.

  A missing display name is returned as an empty string. Throws Error when s
  is not a valid address according to Go's net/mail parser.`, "1.8.1"))

	mailNamespace.InternVar("parse-address-list", parse_address_list_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Parses an RFC 5322 address list and returns a vector of maps.

  Each element has the form {:name display-name :address mailbox}. Throws
  Error when s is not a valid address list according to Go's net/mail parser.`, "1.8.1"))

	mailNamespace.InternVar("parse-date", parse_date_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Parses an RFC 5322 date string and returns a Time.

  Throws Error when s is not a date accepted by Go's net/mail parser.`, "1.8.1").Plus(MakeKeyword("tag"), String{S: "Time"}))

	mailNamespace.InternVar("read-message", read_message_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("source"))),
			`Parses an RFC 5322 message from source and returns its headers and raw body.

  source must be a string or implement io.Reader, such as a string returned by
  joker.pop3/retrieve. The result is a map of the form
  {:headers {"Header-Name" ["value" ...]} :body "raw body"}.

  Header names use Go net/mail's canonical form and header values remain
  vectors so repeated headers are preserved. The complete message body is
  buffered in memory. This function does not parse MIME parts or decode body
  transfer encodings. Throws Error when source is invalid or the headers
  cannot be parsed.`, "1.8.1"))

}
