(memfn)
;; blank line where (defmulti) used to be (it's now supported in eval mode)
(letfn)
(..)
(proxy)
(defstruct)
(with-local-vars)
(definline)
(definterface)
(proxy-super)
(with-open)
(defrecord)

