// This file is generated by generate-std.joke script. Do not edit manually!

package private

import (
	. "github.com/candid82/joker/core"
)

var privateNamespace = GLOBAL_ENV.EnsureNamespace(MakeSymbol("joker.private"))



var types_ Proc

func __types_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 0:
		_res := types()
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	types_ = __types_

	privateNamespace.ResetMeta(MakeMeta(nil, "Provides access to internals of Joker.", "1.0"))

	
	privateNamespace.InternVar("types", types_,
		MakeMeta(
			NewListFrom(NewVectorFrom()),
			`Returns currently registered types as a map.`, "1.0"))

}

func init() {
	privateNamespace.Lazy = Init
}
