(ns derefable-returns)

@(agent 1)
@(send (agent 1) inc)
@(send-off (agent 1) inc)
@(send-via clojure.lang.Agent/pooledExecutor (agent 1) inc)
@(ref 1)
@(promise)
@(deliver (promise) 1)
@(future 1)
@(future-call (fn [] 1))
@(reduced 1)
@(add-watch (atom 1) :watcher (fn [_key _ref _old _new] nil))
@(remove-watch (atom 1) :watcher)
