// This file is generated by generate-std.joke script. Do not edit manually!

package runtime

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of runtime.InternsOrThunks().")
	}
	runtimeNamespace.ResetMeta(MakeMeta(nil, `Reports build-time Go and Joker runtime metadata.`, "1.0"))

	runtimeNamespace.InternVar("go-root", go_root_,
		MakeMeta(
			NewListFrom(NewVectorFrom()),
			`Returns the GOROOT path embedded in the Go toolchain.`, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

	runtimeNamespace.InternVar("go-version", go_version_,
		MakeMeta(
			NewListFrom(NewVectorFrom()),
			`Returns the Go version string used to build Joker.`, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

	runtimeNamespace.InternVar("joker-version", joker_version_,
		MakeMeta(
			NewListFrom(NewVectorFrom()),
			`Returns Joker's raw version string.

  Unlike joker.core/joker-version, this includes the leading "v".`, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

}
