// Generated by gen_code. Don't modify manually!

package core

var sym_1 = &Symbol{ns: nil}

var sym_2 = &Symbol{ns: nil}
var var_2 = &DefExpr{
	name: *sym_2,
	value: &FnExpr{
		//		arities: &FnArityExpr{},
		self: *sym_2,
	}}

func init() {
	_ns := GLOBAL_ENV.CurrentNamespace()

	string_1 := STRINGS.Intern("first")
	sym_1.name = string_1
	v1 := _ns.Intern(*sym_1)
	v1.Value = procFirst

	string_2 := STRINGS.Intern("second")
	sym_2.name = string_2
	v2 := _ns.Intern(*sym_2)
	var_2.vr = v2
}
