// +build !fast_init

package core

import (
	"math/rand"
	"time"
)

var privateMeta Map = EmptyArrayMap().Assoc(KEYWORDS.private, Boolean{B: true}).(Map)

// cycles is true for ProcFn's that refer, directly or indirectly, to
// any invariant initializer, mainly GLOBAL_ENV. If their .Fn fields
// are statically (invariantly) initialized, the Go compiler (as of
// 1.13) will complain about a cycle.
func intern(name string, proc ProcFn, procName string, cycles bool) {
	vr := GLOBAL_ENV.CoreNamespace.Intern(MakeSymbol(name))
	vr.Value = Proc{Fn: proc, Name: procName, Cycles: cycles}
	vr.isPrivate = true
	vr.meta = privateMeta
}

func init() {
	rand.Seed(time.Now().UnixNano())
	GLOBAL_ENV.CoreNamespace.InternVar("*assert*", Boolean{B: true},
		MakeMeta(nil, "When set to logical false, assert is a noop. Defaults to true.", "1.0"))

	intern("list__", procList, "procList", false)
	intern("cons__", procCons, "procCons", false)
	intern("first__", procFirst, "procFirst", false)
	intern("next__", procNext, "procNext", false)
	intern("rest__", procRest, "procRest", false)
	intern("conj__", procConj, "procConj", false)
	intern("seq__", procSeq, "procSeq", false)
	intern("instance?__", procIsInstance, "procIsInstance", false)
	intern("assoc__", procAssoc, "procAssoc", false)
	intern("meta__", procMeta, "procMeta", false)
	intern("with-meta__", procWithMeta, "procWithMeta", false)
	intern("=__", procEquals, "procEquals", false)
	intern("count__", procCount, "procCount", false)
	intern("subvec__", procSubvec, "procSubvec", false)
	intern("cast__", procCast, "procCast", false)
	intern("vec__", procVec, "procVec", false)
	intern("hash-map__", procHashMap, "procHashMap", false)
	intern("hash-set__", procHashSet, "procHashSet", false)
	intern("str__", procStr, "procStr", false)
	intern("symbol__", procSymbol, "procSymbol", false)
	intern("gensym__", procGensym, "procGensym", false)
	intern("keyword__", procKeyword, "procKeyword", false)
	intern("apply__", procApply, "procApply", false)
	intern("lazy-seq__", procLazySeq, "procLazySeq", false)
	intern("delay__", procDelay, "procDelay", false)
	intern("force__", procForce, "procForce", false)
	intern("identical__", procIdentical, "procIdentical", false)
	intern("compare__", procCompare, "procCompare", false)
	intern("zero?__", procIsZero, "procIsZero", false)
	intern("int__", procInt, "procInt", false)
	intern("nth__", procNth, "procNth", false)
	intern("<__", procLt, "procLt", false)
	intern("<=__", procLte, "procLte", false)
	intern(">__", procGt, "procGt", false)
	intern(">=__", procGte, "procGte", false)
	intern("==__", procEq, "procEq", false)
	intern("inc'__", procIncEx, "procIncEx", false)
	intern("inc__", procInc, "procInc", false)
	intern("dec'__", procDecEx, "procDecEx", false)
	intern("dec__", procDec, "procDec", false)
	intern("add'__", procAddEx, "procAddEx", false)
	intern("add__", procAdd, "procAdd", false)
	intern("multiply'__", procMultiplyEx, "procMultiplyEx", false)
	intern("multiply__", procMultiply, "procMultiply", false)
	intern("divide__", procDivide, "procDivide", false)
	intern("subtract'__", procSubtractEx, "procSubtractEx", false)
	intern("subtract__", procSubtract, "procSubtract", false)
	intern("max__", procMax, "procMax", false)
	intern("min__", procMin, "procMin", false)
	intern("pos__", procIsPos, "procIsPos", false)
	intern("neg__", procIsNeg, "procIsNeg", false)
	intern("quot__", procQuot, "procQuot", false)
	intern("rem__", procRem, "procRem", false)
	intern("bit-not__", procBitNot, "procBitNot", false)
	intern("bit-and__", procBitAnd, "procBitAnd", false)
	intern("bit-or__", procBitOr, "procBitOr", false)
	intern("bit-xor_", procBitXor, "procBitXor", false)
	intern("bit-and-not__", procBitAndNot, "procBitAndNot", false)
	intern("bit-clear__", procBitClear, "procBitClear", false)
	intern("bit-set__", procBitSet, "procBitSet", false)
	intern("bit-flip__", procBitFlip, "procBitFlip", false)
	intern("bit-test__", procBitTest, "procBitTest", false)
	intern("bit-shift-left__", procBitShiftLeft, "procBitShiftLeft", false)
	intern("bit-shift-right__", procBitShiftRight, "procBitShiftRight", false)
	intern("unsigned-bit-shift-right__", procUnsignedBitShiftRight, "procUnsignedBitShiftRight", false)
	intern("peek__", procPeek, "procPeek", false)
	intern("pop__", procPop, "procPop", false)
	intern("contains?__", procContains, "procContains", false)
	intern("get__", procGet, "procGet", false)
	intern("dissoc__", procDissoc, "procDissoc", false)
	intern("disj__", procDisj, "procDisj", false)
	intern("find__", procFind, "procFind", false)
	intern("keys__", procKeys, "procKeys", false)
	intern("vals__", procVals, "procVals", false)
	intern("rseq__", procRseq, "procRseq", false)
	intern("name__", procName, "procName", false)
	intern("namespace__", procNamespace, "procNamespace", false)
	intern("find-var__", procFindVar, "procFindVar", true)
	intern("sort__", procSort, "procSort", false)
	intern("eval__", procEval, "procEval", true)
	intern("type__", procType, "procType", false)
	intern("num__", procNumber, "procNumber", false)
	intern("double__", procDouble, "procDouble", false)
	intern("char__", procChar, "procChar", false)
	intern("boolean__", procBoolean, "procBoolean", false)
	intern("numerator__", procNumerator, "procNumerator", false)
	intern("denominator__", procDenominator, "procDenominator", false)
	intern("bigint__", procBigInt, "procBigInt", false)
	intern("bigfloat__", procBigFloat, "procBigFloat", false)
	intern("pr__", procPr, "procPr", true)
	intern("pprint__", procPprint, "procPprint", true)
	intern("newline__", procNewline, "procNewline", true)
	intern("flush__", procFlush, "procFlush", false)
	intern("read__", procRead, "procRead", true)
	intern("read-line__", procReadLine, "procReadLine", true)
	intern("reader-read-line__", procReaderReadLine, "procReaderReadLine", false)
	intern("read-string__", procReadString, "procReadString", true)
	intern("nano-time__", procNanoTime, "procNanoTime", false)
	intern("macroexpand-1__", procMacroexpand1, "procMacroexpand1", true)
	intern("load-string__", procLoadString, "procLoadString", true)
	intern("find-ns__", procFindNamespace, "procFindNamespace", true)
	intern("create-ns__", procCreateNamespace, "procCreateNamespace", true)
	intern("inject-ns__", procInjectNamespace, "procInjectNamespace", true)
	intern("remove-ns__", procRemoveNamespace, "procRemoveNamespace", true)
	intern("all-ns__", procAllNamespaces, "procAllNamespaces", true)
	intern("ns-name__", procNamespaceName, "procNamespaceName", false)
	intern("ns-map__", procNamespaceMap, "procNamespaceMap", false)
	intern("ns-unmap__", procNamespaceUnmap, "procNamespaceUnmap", false)
	intern("var-ns__", procVarNamespace, "procVarNamespace", false)
	intern("refer__", procRefer, "procRefer", false)
	intern("alias__", procAlias, "procAlias", false)
	intern("ns-aliases__", procNamespaceAliases, "procNamespaceAliases", false)
	intern("ns-unalias__", procNamespaceUnalias, "procNamespaceUnalias", false)
	intern("var-get__", procVarGet, "procVarGet", false)
	intern("var-set__", procVarSet, "procVarSet", false)
	intern("ns-resolve__", procNsResolve, "procNsResolve", true)
	intern("array-map__", procArrayMap, "procArrayMap", false)
	intern("buffer__", procBuffer, "procBuffer", false)
	intern("buffered-reader__", procBufferedReader, "procBufferedReader", false)
	intern("ex-info__", procExInfo, "procExInfo", false)
	intern("ex-data__", procExData, "procExData", false)
	intern("ex-cause__", procExCause, "procExCause", false)
	intern("ex-message__", procExMessage, "procExMessage", false)
	intern("regex__", procRegex, "procRegex", false)
	intern("re-seq__", procReSeq, "procReSeq", false)
	intern("re-find__", procReFind, "procReFind", false)
	intern("rand__", procRand, "procRand", false)
	intern("special-symbol?__", procIsSpecialSymbol, "procIsSpecialSymbol", false)
	intern("subs__", procSubs, "procSubs", false)
	intern("intern__", procIntern, "procIntern", false)
	intern("set-meta__", procSetMeta, "procSetMeta", false)
	intern("atom__", procAtom, "procAtom", false)
	intern("deref__", procDeref, "procDeref", false)
	intern("swap__", procSwap, "procSwap", false)
	intern("swap-vals__", procSwapVals, "procSwapVals", false)
	intern("reset__", procReset, "procReset", false)
	intern("reset-vals__", procResetVals, "procResetVals", false)
	intern("alter-meta__", procAlterMeta, "procAlterMeta", false)
	intern("reset-meta__", procResetMeta, "procResetMeta", false)
	intern("empty__", procEmpty, "procEmpty", false)
	intern("bound?__", procIsBound, "procIsBound", false)
	intern("format__", procFormat, "procFormat", false)
	intern("load-file__", procLoadFile, "procLoadFile", true)
	intern("load-lib-from-path__", procLoadLibFromPath, "procLoadLibFromPath", true)
	intern("reduce-kv__", procReduceKv, "procReduceKv", false)
	intern("slurp__", procSlurp, "procSlurp", false)
	intern("spit__", procSpit, "procSpit", false)
	intern("shuffle__", procShuffle, "procShuffle", false)
	intern("realized?__", procIsRealized, "procIsRealized", false)
	intern("derive-info__", procDeriveInfo, "procDeriveInfo", false)
	intern("joker-version__", procJokerVersion, "procJokerVersion", false)

	intern("hash__", procHash, "procHash", false)

	intern("index-of__", procIndexOf, "procIndexOf", false)
	intern("lib-path__", procLibPath, "procLibPath", true)
	intern("intern-fake-var__", procInternFakeVar, "procInternFakeVar", true)
	intern("parse__", procParse, "procParse", true)
	intern("inc-problem-count__", procIncProblemCount, "procIncProblemCount", false)
	intern("types__", procTypes, "procTypes", false)
	intern("go__", procGo, "procGo", false)
	intern("<!__", procReceive, "procReceive", false)
	intern(">!__", procSend, "procSend", false)
	intern("chan__", procCreateChan, "procCreateChan", false)
	intern("close!__", procCloseChan, "procCloseChan", false)

	intern("go-spew__", procGoSpew, "procGoSpew", false)
}
