// Generated by gen_types. Don't modify manually!

package core

func (x *List) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *ArrayMapSeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *ArrayMap) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *HashMap) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *ExInfo) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *Fn) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *Var) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Nil) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *Ratio) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *BigInt) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *BigFloat) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Char) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Double) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Int) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Boolean) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Time) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Keyword) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *Regex) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Symbol) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x String) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x Comment) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *LazySeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *MappingSeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *ArraySeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *ConsSeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *NodeSeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *ArrayNodeSeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *MapSet) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *Vector) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *VectorSeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}

func (x *VectorRSeq) WithInfo(info *ObjectInfo) Object {
	x.info = info
	return x
}
