// This file is generated by generate-std.joke script. Do not edit manually!

package yaml

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of yaml.InternsOrThunks().")
	}
	yamlNamespace.ResetMeta(MakeMeta(nil, `Encodes Joker values to YAML and decodes YAML strings into Joker values.`, "1.0"))

	yamlNamespace.InternVar("read-string", read_string_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Parses YAML string s and returns the corresponding Joker value.

  YAML mappings become maps, sequences become vectors, scalars become their
  nearest Joker values, and null becomes nil. Throws Error when s is invalid
  YAML.`, "1.0"))

	yamlNamespace.InternVar("write-string", write_string_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("v"))),
			`Returns the YAML encoding of v.

  Keywords are encoded without their leading colon, map keys are converted to
  strings, and vectors become YAML sequences. Throws Error when v cannot be
  encoded.`, "1.0"))

}
