// This file is generated by generate-std.joke script. Do not edit manually!

package io

import (
	. "github.com/candid82/joker/core"
	"io"
)


var __copy__P ProcFn = __copy_
var copy_ Proc = Proc{Fn: __copy__P, Name: "copy_", Package: "std/io"}

func __copy_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 2:
		dst := ExtractIOWriter(_args, 0)
		src := ExtractIOReader(_args, 1)
		 n, err := io.Copy(dst, src)
		PanicOnErr(err)
		_res := int(n)
		return MakeInt(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var ioNamespace = GLOBAL_ENV.EnsureNamespace(MakeSymbol("joker.io"))

func init() {
	ioNamespace.Lazy = Init
}
