// This file is generated by generate-std.joke script. Do not edit manually!

package smtp

import (
	. "github.com/candid82/joker/core"
)

var __send__P ProcFn = __send_
var send_ Proc = Proc{Fn: __send__P, Name: "send_", Package: "std/smtp"}

func __send_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		request := ExtractMap(_args, 0)
		_res := sendMessage(request)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var smtpNamespace = GLOBAL_ENV.EnsureSymbolIsLib(MakeSymbol("joker.smtp"))

func init() {
	smtpNamespace.Lazy = Init
}
