// This file is generated by generate-std.joke script. Do not edit manually!

package net

import (
  
  . "github.com/candid82/joker/core"
)

var netNamespace = GLOBAL_ENV.EnsureNamespace(MakeSymbol("joker.go.net"))

var LookupMX_ Proc = func(args []Object) Object {
  c := len(args)
  switch  {
  case c == 1:
    
    s := ExtractString(args, 0)
    res := lookupMX(s)
    return res

  default:
    PanicArity(c)
  }
  return NIL
}


func init() {

netNamespace.ResetMeta(MakeMeta(nil, "DRAFT: Implements just joker.go.net/LookupMX() so far.", "1.0"))

netNamespace.InternVar("LookupMX", LookupMX_,
  MakeMeta(
    NewListFrom(NewVectorFrom(MakeSymbol("s"))),
    `DRAFT: Returns vector of MX ({ :Host <hostname>, :Pref <preference>}) and error object (or nil) from net.LookupMX(s) as { :res <mx> :err <err> }`, "1.0"))

}
