// This file is generated by generate-std.joke script. Do not edit manually!

package bolt

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of bolt.InternsOrThunks().")
	}
	boltNamespace.ResetMeta(MakeMeta(nil, `Provides a small string-oriented API for the Bolt embedded key/value database.

         Example:

         user=> (def db (joker.bolt/open "bolt.db" 0600))
         #'user/db
         user=> (joker.bolt/create-bucket db "users")
         nil
         user=> (def id (joker.bolt/next-sequence db "users"))
         #'user/id
         user=> id
         1
         user=> (joker.bolt/put db "users" (str id) (joker.json/write-string {:id id :name "Joe Black"}))
         nil
         user=> (joker.json/read-string (joker.bolt/get db "users" (str id)))
         {"id" 1, "name" "Joe Black"}`, "1.0"))

	boltNamespace.InternVar("by-prefix", by_prefix_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("bucket").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("prefix").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Returns key/value pairs from bucket whose keys start with prefix.

  Results are returned as a vector of [key value] vectors in Bolt key order.
  Passing the empty string returns all key/value pairs in the bucket. Throws
  Error when bucket does not exist or the transaction fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Vec"}))

	boltNamespace.InternVar("close", close_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol))),
			`Closes db and releases its database resources.

  Blocks until open transactions finish, then releases the file lock. Throws
  Error if closing fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	boltNamespace.InternVar("create-bucket", create_bucket_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("name").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Creates bucket name and returns nil.

  Throws Error if the bucket already exists, if name is blank or too long, or
  if the transaction fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	boltNamespace.InternVar("create-bucket-if-not-exists", create_bucket_if_not_exists_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("name").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Creates bucket name when needed and returns nil.

  Does nothing when the bucket already exists. Throws Error if name is blank or
  too long, or if the transaction fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	boltNamespace.InternVar("delete", delete_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("bucket").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("key").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Removes key from bucket and returns nil.

  Missing keys are ignored. Throws Error when bucket does not exist or the
  transaction fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	boltNamespace.InternVar("delete-bucket", delete_bucket_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("name").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Deletes bucket name and returns nil.

  Throws Error when the bucket does not exist or the transaction fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Nil"}))

	boltNamespace.InternVar("get", get_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("bucket").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("key").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Returns the string value stored at key in bucket.

  Returns nil when key does not exist. Throws Error when bucket does not exist
  or the transaction fails.`, "1.0"))

	boltNamespace.InternVar("next-sequence", next_sequence_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("bucket").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Returns the next auto-incrementing integer for bucket.

  Each call advances the bucket sequence counter inside a write transaction.
  Throws Error when bucket does not exist or the transaction fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Int"}))

	boltNamespace.InternVar("open", open_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("filename").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("mode").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Int"}).(Map)).(Symbol))),
			`Opens the database file at filename and returns a BoltDB handle.

  If the file does not exist, it is created with mode before the process umask
  is applied. mode is normally written as an octal literal such as 0600.
  Throws Error when the database cannot be opened.

  The underlying database uses an exclusive file lock; because this wrapper uses
  Bolt's default options, open may wait indefinitely for another process to
  release the same database file.

  Example:
    (def db (joker.bolt/open "app.db" 0600))`, "1.0").Plus(MakeKeyword("tag"), String{S: "BoltDB"}))

	boltNamespace.InternVar("put", put_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("db").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "BoltDB"}).(Map)).(Symbol), MakeSymbol("bucket").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("key").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("value").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Stores value at key in bucket and returns nil.

  Keys and values are strings stored as raw bytes. Replaces any previous value
  for key. Throws Error when bucket does not exist, when key is blank or too
  large, when value is too large, or when the transaction fails.`, "1.0").Plus(MakeKeyword("tag"), String{S: "Nil"}))

}
