// This file is generated by generate-std.joke script. Do not edit manually!

package json

import (
	. "github.com/candid82/joker/core"
)

var jsonNamespace = GLOBAL_ENV.EnsureNamespace(MakeSymbol("joker.json"))



var read_string_ Proc

func __read_string_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		s := ExtractString(_args, 0)
		_res := readString(s, nil)
		return _res

	case _c == 2:
		s := ExtractString(_args, 0)
		opts := ExtractMap(_args, 1)
		_res := readString(s, opts)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var write_string_ Proc

func __write_string_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		v := ExtractObject(_args, 0)
		_res := writeString(v)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	read_string_ = __read_string_
	write_string_ = __write_string_

	jsonNamespace.ResetMeta(MakeMeta(nil, `Implements encoding and decoding of JSON as defined in RFC 4627.`, "1.0"))

	
	jsonNamespace.InternVar("read-string", read_string_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s")), NewVectorFrom(MakeSymbol("s"), MakeSymbol("opts"))),
			`Parses the JSON-encoded data and return the result as a Joker value.
  Optional opts map may have the following keys:
  :keywords? - if true, JSON keys will be converted from strings to keywords.`, "1.0"))

	jsonNamespace.InternVar("write-string", write_string_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("v"))),
			`Returns the JSON encoding of v.`, "1.0"))

}

func init() {
	jsonNamespace.Lazy = Init
}
