(inc (list 1))
(inc (cons 1 []))
(inc (next []))
(inc (rest []))
(inc (conj [] 1))
(inc (nfirst []))
(inc (nnext []))
(inc (seq []))
(inc (instance? Seq []))
(inc (seq? []))
(inc (char? []))
(inc (map? []))
(inc (vector? []))
(inc (ex-info "" {}))
(inc (assoc [] 0 1))
(inc (meta []))
(inc (butlast []))
(inc (vec []))
(inc (vector 1))
(inc (hash-set 1))
(inc (nil? 1))
(inc (false? 1))
(inc (true? 1))
(inc (boolean? 1))
(inc (any? 1))
(inc (not 1))
(inc (some? 1))
(inc (str))
(inc (symbol? 1))
(inc (keyword? 1))
(inc (symbol 1))
(inc (gensym))
(inc (print "test"))
(inc (prn "test"))
(inc (println "test"))
(inc (keyword "t"))
(inc (list* 1 []))
(inc (chunked-seq? 1))
(inc (concat []))
(inc (delay? 1))
(inc (identical? 1 2))
(inc (= 1 2))
(inc (not= 1 2))
(map (compare 1 2))
(inc (zero? 1))
(map (count []))
(map (int 1))
(inc (< 1 2))
(map (inc' 1))
(map (inc 1))
(inc (reverse []))
(map (+' 1))
(map (+ 1))
(map (*' 1))
(map (* 1))
(map (/ 1))
(map (-' 1))
(map (- 1))
(inc (<= 1 2))
(inc (> 1 2))
(inc (>= 1 2))
(inc (== 1 2))
(map (max 1 2))
(map (min 1 2))
(map (dec' 1))
(map (dec 1))
(inc (pos? 1))
(inc (neg? 1))
(map (quot 1 2))
(map (rem 1 2))
(map (bit-not 1))
(map (bit-and 1 2))
(map (bit-or 1 2))
(map (bit-xor 1 2))
(map (bit-and-not 1 2))
(map (bit-clear 1 2))
(map (bit-set 1 2))
(map (bit-flip 1 2))
(map (bit-test 1 2))
(map (bit-shift-left 1 2))
(map (bit-shift-right 1 2))
(map (unsigned-bit-shift-right 1 2))
(map (integer? 1))
(map (even? 1))
(map (odd? 1))
(map (int? 1))
(map (pos-int? 1))
(map (neg-int? 1))
(map (nat-int? 1))
(map (double? 1))


(inc (map inc nil))
