// This file is generated by generate-std.joke script. Do not edit manually!

//go:build !gen_code
// +build !gen_code

package html

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running fast version of html.InternsOrThunks().")
	}
	STD_thunk_html_escape__var = __escape_
	STD_thunk_html_unescape__var = __unescape_
}
