(ns typed-core-returns-cljs)

(+ (unchecked-add-int 1 2)
   (unchecked-int 3)
   (long 4))

(subs (munge "a-b") 0)
(keys (sorted-map :a 1))
(disj (sorted-set :a) :a)
(first (replicate 1 :x))
@(ensure-reduced 1)

(+ (unchecked-inc 2)
   (compare-indexed [1] [1])
   (tail-off [1])
   (array-index-of [1] 1)
   (array-index-of-nil? [nil])
   (array-index-of-keyword? [:a] :a)
   (array-index-of-symbol? ['a] 'a)
   (array-index-of-identical? [1] 1)
   (array-index-of-equiv? [1] 1)
   (system-time)
   (divide 4 2)
   (unsafe-bit-and 1 1)
   (fix 1.2)
   (m3-hash-int 1)
   (m3-hash-unencoded-chars "abc")
   (hash-string nil)
   (hash-string* nil)
   (compare-symbols 'a 'b)
   (compare-keywords :a :b)
   (unchecked-char 65))

(when (compare-and-set! (atom 0) 0 1)
  true)
(when (coercive-boolean 1) true)
(when (coercive-not nil) true)
(when (coercive-= 1 "1") true)
(when (coercive-not= 1 2) true)

(+ (inst-ms #inst "2020-01-01T00:00:00.000-00:00") 1)
(when (inst? #inst "2020-01-01T00:00:00.000-00:00") true)
(when (uuid? #uuid "00000000-0000-0000-0000-000000000000") true)
(comp (map inc) (filter pos?) (take 1) (drop 0) (partition-all 2) (keep identity) (dedupe))
(subs (pr-str* :x) 0)
(subs (js-str :x) 0)
(set-validator! (atom 1) nil)
