// This file is generated by generate-std.joke script. Do not edit manually!

package csv

import (
	. "github.com/candid82/joker/core"
)

var csvNamespace = GLOBAL_ENV.EnsureNamespace(MakeSymbol("joker.csv"))



var csv_seq_ Proc = func(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		rdr := ExtractIOReader(_args, 0)
		_res := csvSeq(rdr)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func init() {

	csvNamespace.ResetMeta(MakeMeta(nil, "Reads and writes comma-separated values (CSV) files as defined in RFC 4180.", "1.0"))

	
	csvNamespace.InternVar("csv-seq", csv_seq_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("rdr"))),
			`Returns the csv records from rdr as a lazy sequence.
  rdr must implement io.Reader.`, "1.0"))

}
