// This file is generated by generate-std.joke script. Do not edit manually!

package mime

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of mime.InternsOrThunks().")
	}
	mimeNamespace.ResetMeta(MakeMeta(nil, `Parses MIME media types, entities, message bodies, and attachments.`, "1.0"))

	mimeNamespace.InternVar("attachments", attachments_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("entity").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol)), NewVectorFrom(MakeSymbol("entity").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol), MakeSymbol("opts").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol))),
			`Returns attachment-like leaf entities from a MIME entity tree.

  A part is included when Content-Disposition is attachment. By default inline
  parts with a filename are also included, which covers common inline images.

  opts may contain:
  - include-inline? - false to exclude inline/file-name parts; defaults to true`, "1.9.0").Plus(MakeKeyword("tag"), String{S: "Vec"}))

	mimeNamespace.InternVar("body", body_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("entity").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol)), NewVectorFrom(MakeSymbol("entity").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol), MakeSymbol("opts").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol))),
			`Extracts human-readable body content from a MIME entity tree.

  Returns {:text text-or-nil :html html-or-nil}. Attachment-like parts are
  ignored. The function handles both multipart and non-multipart entities;
  text/plain leaves become :text and text/html leaves become :html. If multiple
  matching leaves exist, the first value of each type is returned.`, "1.9.0").Plus(MakeKeyword("tag"), String{S: "Map"}))

	mimeNamespace.InternVar("decode-transfer-encoding", decode_transfer_encoding_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("encoding").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Object"}).(Map)).(Symbol), MakeSymbol("content").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Decodes content according to a MIME Content-Transfer-Encoding value.

  Supported encodings are nil/empty, 7bit, 8bit, binary, base64, and
  quoted-printable. The returned string contains raw decoded bytes and may be
  binary data. Throws Error for invalid encoded data or unsupported encodings.`, "1.9.0").Plus(MakeKeyword("tag"), String{S: "String"}))

	mimeNamespace.InternVar("parse-media-type", parse_media_type_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol))),
			`Parses a MIME media type or disposition value and returns
  {:type type :params {name value ...}}.

  The input may be a Content-Type value such as
  "text/plain; charset=utf-8" or a Content-Disposition value such as
  "attachment; filename=report.pdf". Parameter names are lower-case as
  returned by Go's mime.ParseMediaType. Throws Error when s is invalid.`, "1.9.0").Plus(MakeKeyword("tag"), String{S: "Map"}))

	mimeNamespace.InternVar("read-entity", read_entity_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("headers").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol), MakeSymbol("body").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol)), NewVectorFrom(MakeSymbol("headers").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol), MakeSymbol("body").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "String"}).(Map)).(Symbol), MakeSymbol("opts").WithMeta(EmptyArrayMap().Assoc(MakeKeyword("tag"), String{S: "Map"}).(Map)).(Symbol))),
			`Parses a MIME entity from headers and body and returns a recursive map.

  headers must be a map like {"Header-Name" ["value" ...]}; body is the
  raw entity body. Non-multipart entities contain decoded :content and :size.
  Multipart entities contain :parts. Content-Transfer-Encoding is decoded for
  leaf entities.

  Entity maps contain keys such as:
  - :headers
  - :content-type
  - :content-type-params
  - :disposition
  - :disposition-params
  - :filename
  - :safe-filename
  - :content-transfer-encoding
  - :content
  - :size
  - :path
  - :parts

  Missing Content-Type defaults to text/plain. Binary content is represented as
  a Joker string containing raw bytes.

  opts may contain:
  - include-content? - false to omit :content from leaf entities
  - max-depth - maximum multipart nesting depth; defaults to 32
  - max-part-bytes - maximum bytes to buffer for any MIME part; nil/unset means
    unlimited`, "1.9.0").Plus(MakeKeyword("tag"), String{S: "Map"}))

}
