// This file is generated by generate-std.joke script. Do not edit manually!

package mime

import (
	. "github.com/candid82/joker/core"
)

var __attachments__P ProcFn = __attachments_
var attachments_ Proc = Proc{Fn: __attachments__P, Name: "attachments_", Package: "std/mime"}

func __attachments_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		entity := ExtractMap(_args, 0)
		_res := attachments(entity, EmptyArrayMap())
		return _res

	case _c == 2:
		entity := ExtractMap(_args, 0)
		opts := ExtractMap(_args, 1)
		_res := attachments(entity, opts)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __body__P ProcFn = __body_
var body_ Proc = Proc{Fn: __body__P, Name: "body_", Package: "std/mime"}

func __body_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		entity := ExtractMap(_args, 0)
		_res := body(entity, EmptyArrayMap())
		return _res

	case _c == 2:
		entity := ExtractMap(_args, 0)
		opts := ExtractMap(_args, 1)
		_res := body(entity, opts)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __decode_transfer_encoding__P ProcFn = __decode_transfer_encoding_
var decode_transfer_encoding_ Proc = Proc{Fn: __decode_transfer_encoding__P, Name: "decode_transfer_encoding_", Package: "std/mime"}

func __decode_transfer_encoding_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 2:
		encoding := ExtractObject(_args, 0)
		content := ExtractString(_args, 1)
		_res := decodeTransferEncoding(encoding, content)
		return MakeString(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

var __parse_media_type__P ProcFn = __parse_media_type_
var parse_media_type_ Proc = Proc{Fn: __parse_media_type__P, Name: "parse_media_type_", Package: "std/mime"}

func __parse_media_type_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		s := ExtractString(_args, 0)
		_res := parseMediaType(s)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __read_entity__P ProcFn = __read_entity_
var read_entity_ Proc = Proc{Fn: __read_entity__P, Name: "read_entity_", Package: "std/mime"}

func __read_entity_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 2:
		headers := ExtractMap(_args, 0)
		body := ExtractString(_args, 1)
		_res := readEntity(headers, body, EmptyArrayMap())
		return _res

	case _c == 3:
		headers := ExtractMap(_args, 0)
		body := ExtractString(_args, 1)
		opts := ExtractMap(_args, 2)
		_res := readEntity(headers, body, opts)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var mimeNamespace = GLOBAL_ENV.EnsureSymbolIsLib(MakeSymbol("joker.mime"))

func init() {
	mimeNamespace.Lazy = Init
}
