package main

import (
	"io/ioutil"
	"strings"
)

var template string = `// Generated by gen_data. Don't modify manually!

package core

var {name}Data = []byte("{content}")
`

const hextable = "0123456789abcdef"

func main() {
	files, err := ioutil.ReadDir("data")
	if err != nil {
		panic(err)
	}
	for _, f := range files {
		content, err := ioutil.ReadFile("data/" + f.Name())
		if err != nil {
			panic(err)
		}
		dst := make([]byte, len(content)*4)
		for i, v := range content {
			dst[i*4] = '\\'
			dst[i*4+1] = 'x'
			dst[i*4+2] = hextable[v>>4]
			dst[i*4+3] = hextable[v&0x0f]
		}
		name := f.Name()[0 : len(f.Name())-5] // assumes .joke extension
		fileContent := strings.Replace(template, "{name}", name, 1)
		fileContent = strings.Replace(fileContent, "{content}", string(dst), 1)
		ioutil.WriteFile("a_"+name+"_data.go", []byte(fileContent), 0666)
	}
}
