// This file is generated by generate-std.joke script. Do not edit manually!

package markdown

import (
	. "github.com/candid82/joker/core"
)

var __convert_string__P ProcFn = __convert_string_
var convert_string_ Proc = Proc{Fn: __convert_string__P, Name: "convert_string_", Package: "std/markdown"}

func __convert_string_(_args []Object) Object {
	_c := len(_args)
	switch {
	case _c == 1:
		s := ExtractString(_args, 0)
		_res := convertString(s)
		return MakeString(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var markdownNamespace = GLOBAL_ENV.EnsureSymbolIsLib(MakeSymbol("joker.markdown"))

func init() {
	markdownNamespace.Lazy = Init
}
