// This file is generated by generate-std.joke script. Do not edit manually!

package markdown

import (
	"fmt"
	. "github.com/candid82/joker/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of markdown.InternsOrThunks().")
	}
	markdownNamespace.ResetMeta(MakeMeta(nil, `Implements GitHub Flavored Markdown rendering.`, "1.0"))

	markdownNamespace.InternVar("convert-string", convert_string_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s")), NewVectorFrom(MakeSymbol("s"), MakeSymbol("opts"))),
			`Returns the HTML rendering of Markdown string s `+"`"+`opts`+"`"+` is an optional map of boolean rendering options (all default to tru to `+"`"+`true`+"`"+`)

  :with-hard-wraps? - Render newlines as <br>.
  :with-xhtml? - Render as XHTML.
  :with-unsafe? - When false, all raw html will be omitted from the output. When true html is passed through unchanged.
  `, "1.0").Plus(MakeKeyword("tag"), String{S: "String"}))

}
